updates:
- directory: /
  package-ecosystem: go-mod
  schedule:
    interval: daily
- directory: /
  package-ecosystem: github-actions
  schedule:
    interval: daily
- directory: /
  package-ecosystem: docker
  schedule:
    interval: daily
version: 2
